services:
  - type: web
    name: contact-manager-backend
    buildCommand: ./gradlew build -x test
    startCommand: java -jar build/libs/contactmanager-0.0.1-SNAPSHOT.jar
    plan: free
    region: oregon
